enabled: true
dropdown:
  enabled: true
navbar:
  title: Andrew Benson
  auth_link:
    enabled: false
    login_slug: login
    login_label: Login
footer:
  copyright: Andrew Benson
  copyright_start_year: 2018
post:
  navigation: true
  taxonomy: true
# listing_title:
#   taxonomy:
#     category: 'Category: '
#     tag: 'Tag: '
#   blogs: 'Posts'
pagination:
  count: 10

social:
    twitter:
      title: Twitter
      url: https://twitter.com/AndrewBenson
      icon: fa-twitter
      rel: me
    linkedin:
      title: LinkedIn
      url: https://linkedin.com/in/abenson
      icon: fa-linkedin-in
      rel: me