title: 'Andrew Benson'
default_lang: en
author:
  name: 'Andrew Benson'
  email: andrew@benson.vc
taxonomies:
  - category
  - tag
metadata:
  description: ''
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
